---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-app-scaled-object
  namespace: app
spec:
  # The name of the deployment
  scaleTargetRef:
    name: example-app

  # How often to check the custom metric
  pollingInterval: 7

  # Only affects 0->1 and 1->0 cases
  cooldownPeriod: 15

  # Replica interval
  minReplicaCount: 2
  maxReplicaCount: 100

  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        # More aggressive scale down
        scaleDown:
          stabilizationWindowSeconds: 15
          policies:
          - type: Pods
            value: 5
            periodSeconds: 5
          - type: Percent
            value: 50
            periodSeconds: 10
  triggers:
    - type: prometheus
      useCachedMetrics: false
      metricType: AverageValue
      metadata:
        # Check the in-cluster Prometheus
        serverAddress: http://prom-stack-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        metricName: response_time
        threshold: "100"
        query: avg(http_response_time_ms{service="example-app"})
