---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-app-scaled-object
  namespace: app
spec:
  scaleTargetRef:
    name: example-app
  pollingInterval: 7
  cooldownPeriod: 15
  minReplicaCount: 2
  maxReplicaCount: 100
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 15
          policies:
          - type: Pods
            value: 5
            periodSeconds: 5
          - type: Percent
            value: 50
            periodSeconds: 10
  triggers:
    - type: prometheus
      useCachedMetrics: false
      metricType: AverageValue
      metadata:
        serverAddress: http://prom-stack-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        metricName: response_time
        threshold: "100"
        query: avg(http_response_time_ms{service="example-app"})

